# Generated by Django 5.2.5 on 2025-09-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this variant from the frontend'),
        ),
    ]
